# Generated by Django 4.1.4 on 2022-12-17 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BonusCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, unique=True, verbose_name='Серия карты')),
                ('expiry', models.DateTimeField(auto_now=True, verbose_name='Дата окончания использования')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата выпуска карты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата использования')),
                ('sum_of_bonus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('A', 'Activated'), ('D', 'Disabled'), ('N', 'Not_activated')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(max_length=35, verbose_name='Name')),
                ('shopping_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_card', to='cards.bonuscard', verbose_name='Карта')),
            ],
        ),
    ]
