# Generated by Django 4.1.4 on 2022-12-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuscard',
            name='expiry',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата выпуска карты'),
        ),
        migrations.AlterField(
            model_name='bonuscard',
            name='number',
            field=models.CharField(max_length=16, verbose_name='Серия карты'),
        ),
        migrations.AlterField(
            model_name='bonuscard',
            name='status',
            field=models.CharField(choices=[('Activated', 'Activated'), ('Disabled', 'Disabled'), ('Not activated', 'Not activated')], default='Not activated', max_length=13),
        ),
    ]
