# Generated by Django 4.1.4 on 2022-12-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_bonuscard_expiry_alter_bonuscard_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuscard',
            name='expiry',
            field=models.DateTimeField(verbose_name='Дата выпуска карты'),
        ),
    ]
