# Generated by Django 4.1.4 on 2022-12-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_bonuscard_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuscard',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания активности'),
        ),
    ]
